Import('*')

SimObject('PipelineMiniCPU.py', sim_objects=['PipelineMiniCPU'])

Source('pipeline_mini_cpu.cc')
Source('pipeline/frontend_fetch_unit.cc')
Source('pipeline/compressed_decode.cc')
Source('pipeline/pipeline_core.cc')
Source('pipeline/stage_if.cc')
Source('pipeline/stage_id.cc')
Source('pipeline/stage_ex.cc')
Source('pipeline/stage_mem.cc')
Source('pipeline/stage_wb.cc')
Source('pipeline/hazard_unit.cc')
Source('pipeline/forwarding_unit.cc')
Source('pipeline/memory_backend_local.cc')
Source('memory/dut_kui_memory_model.cc')
Source('memory/dut_kui_data_crossbar.cc')
Source('memory/sram_converter_32to256.cc')
Source('hc/hc_cbu.cc')
Source('hc/hc_router.cc')
Source('sau/sau_cbu.cc')
Source('sau/stub_sau.cc')
Source('veu/veu_cbu.cc')
Source('veu/fake_veu.cc')
Source('veu/timing_veu.cc')
Source('veu/veu_functional.cc')
Source('veu/veu_timing_profile.cc')

GTest('brs_frontend_fetch_unit.test',
      'pipeline/frontend_fetch_unit.test.cc',
      'pipeline/frontend_fetch_unit.cc')

GTest('brs_compressed_decode.test',
      'pipeline/compressed_decode.test.cc',
      'pipeline/compressed_decode.cc')

GTest('brs_dut_kui_memory_model.test',
      'memory/dut_kui_memory_model.test.cc',
      'memory/dut_kui_memory_model.cc',
      'memory/dut_kui_data_crossbar.cc',
      'memory/sram_converter_32to256.cc')

GTest('brs_sram_converter_32to256.test',
      'memory/sram_converter_32to256.test.cc',
      'memory/sram_converter_32to256.cc')

GTest('brs_dut_kui_data_crossbar.test',
      'memory/dut_kui_data_crossbar.test.cc',
      'memory/dut_kui_data_crossbar.cc')

GTest('brs_program_image.test',
      'pipeline/program_image.test.cc')

GTest('brs_veu_protocol.test',
      'veu/veu_protocol.test.cc')

GTest('brs_veu_decode.test',
      'pipeline/veu_decode.test.cc')

GTest('brs_veu_cbu.test',
      'veu/veu_cbu.test.cc',
      'hc/hc_cbu.cc',
      'veu/veu_cbu.cc')

GTest('brs_hc_cbu.test',
      'hc/hc_cbu.test.cc',
      'hc/hc_cbu.cc')

GTest('brs_hc_router.test',
      'hc/hc_router.test.cc',
      'hc/hc_router.cc')

GTest('brs_hazard_forwarding.test',
      'pipeline/hazard_forwarding.test.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc')

GTest('brs_fake_veu.test',
      'veu/fake_veu.test.cc',
      'hc/hc_cbu.cc',
      'veu/fake_veu.cc',
      'veu/veu_cbu.cc')

GTest('brs_timing_veu.test',
      'veu/timing_veu.test.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')

GTest('brs_veu_issue.test',
      'pipeline/veu_issue.test.cc')

GTest('brs_sau_decode.test',
      'pipeline/sau_decode.test.cc')

GTest('brs_sau_cbu.test',
      'sau/sau_cbu.test.cc',
      'hc/hc_cbu.cc',
      'sau/sau_cbu.cc')

GTest('brs_stub_sau.test',
      'sau/stub_sau.test.cc',
      'sau/stub_sau.cc')

GTest('brs_sau_issue.test',
      'pipeline/sau_issue.test.cc')

GTest('brs_pipeline_sau.test',
      'pipeline/pipeline_sau.test.cc',
      'pipeline/pipeline_core.cc',
      'pipeline/stage_if.cc',
      'pipeline/stage_id.cc',
      'pipeline/compressed_decode.cc',
      'pipeline/stage_ex.cc',
      'pipeline/stage_mem.cc',
      'pipeline/stage_wb.cc',
      'pipeline/frontend_fetch_unit.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc',
      'pipeline/memory_backend_local.cc',
      'hc/hc_cbu.cc',
      'hc/hc_router.cc',
      'sau/sau_cbu.cc',
      'sau/stub_sau.cc',
      'veu/veu_cbu.cc',
      'veu/fake_veu.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')

GTest('brs_pipeline_veu_stall.test',
      'pipeline/pipeline_veu_stall.test.cc',
      'pipeline/pipeline_veu_async.test.cc',
      'pipeline/pipeline_veu_dmem_lock.test.cc',
      'pipeline/pipeline_core.cc',
      'pipeline/stage_if.cc',
      'pipeline/stage_id.cc',
      'pipeline/compressed_decode.cc',
      'pipeline/stage_ex.cc',
      'pipeline/stage_mem.cc',
      'pipeline/stage_wb.cc',
      'pipeline/frontend_fetch_unit.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc',
      'pipeline/memory_backend_local.cc',
      'hc/hc_cbu.cc',
      'hc/hc_router.cc',
      'sau/sau_cbu.cc',
      'sau/stub_sau.cc',
      'veu/veu_cbu.cc',
      'veu/fake_veu.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')

GTest('brs_pipeline_rv32m.test',
      'pipeline/pipeline_rv32m.test.cc',
      'pipeline/pipeline_core.cc',
      'pipeline/stage_if.cc',
      'pipeline/stage_id.cc',
      'pipeline/compressed_decode.cc',
      'pipeline/stage_ex.cc',
      'pipeline/stage_mem.cc',
      'pipeline/stage_wb.cc',
      'pipeline/frontend_fetch_unit.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc',
      'pipeline/memory_backend_local.cc',
      'hc/hc_cbu.cc',
      'hc/hc_router.cc',
      'sau/sau_cbu.cc',
      'sau/stub_sau.cc',
      'veu/veu_cbu.cc',
      'veu/fake_veu.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')

GTest('brs_pipeline_lsu_timing.test',
      'pipeline/pipeline_lsu_timing.test.cc',
      'pipeline/pipeline_core.cc',
      'pipeline/stage_if.cc',
      'pipeline/stage_id.cc',
      'pipeline/compressed_decode.cc',
      'pipeline/stage_ex.cc',
      'pipeline/stage_mem.cc',
      'pipeline/stage_wb.cc',
      'pipeline/frontend_fetch_unit.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc',
      'pipeline/memory_backend_local.cc',
      'hc/hc_cbu.cc',
      'hc/hc_router.cc',
      'sau/sau_cbu.cc',
      'sau/stub_sau.cc',
      'veu/veu_cbu.cc',
      'veu/fake_veu.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')

GTest('brs_pipeline_csr_trap.test',
      'pipeline/pipeline_csr_trap.test.cc',
      'pipeline/pipeline_core.cc',
      'pipeline/stage_if.cc',
      'pipeline/stage_id.cc',
      'pipeline/compressed_decode.cc',
      'pipeline/stage_ex.cc',
      'pipeline/stage_mem.cc',
      'pipeline/stage_wb.cc',
      'pipeline/frontend_fetch_unit.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc',
      'pipeline/memory_backend_local.cc',
      'hc/hc_cbu.cc',
      'hc/hc_router.cc',
      'sau/sau_cbu.cc',
      'sau/stub_sau.cc',
      'veu/veu_cbu.cc',
      'veu/fake_veu.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')

GTest('brs_pipeline_control_fp.test',
      'pipeline/pipeline_control_fp.test.cc',
      'pipeline/pipeline_core.cc',
      'pipeline/stage_if.cc',
      'pipeline/stage_id.cc',
      'pipeline/compressed_decode.cc',
      'pipeline/stage_ex.cc',
      'pipeline/stage_mem.cc',
      'pipeline/stage_wb.cc',
      'pipeline/frontend_fetch_unit.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc',
      'pipeline/memory_backend_local.cc',
      'hc/hc_cbu.cc',
      'hc/hc_router.cc',
      'sau/sau_cbu.cc',
      'sau/stub_sau.cc',
      'veu/veu_cbu.cc',
      'veu/fake_veu.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')

GTest('brs_pipeline_veu_writeback.test',
      'pipeline/pipeline_veu_writeback.test.cc',
      'pipeline/pipeline_core.cc',
      'pipeline/stage_if.cc',
      'pipeline/stage_id.cc',
      'pipeline/compressed_decode.cc',
      'pipeline/stage_ex.cc',
      'pipeline/stage_mem.cc',
      'pipeline/stage_wb.cc',
      'pipeline/frontend_fetch_unit.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc',
      'pipeline/memory_backend_local.cc',
      'hc/hc_cbu.cc',
      'hc/hc_router.cc',
      'sau/sau_cbu.cc',
      'sau/stub_sau.cc',
      'veu/veu_cbu.cc',
      'veu/fake_veu.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')

GTest('brs_pipeline_veu_end_to_end.test',
      'pipeline/pipeline_veu_end_to_end.test.cc',
      'pipeline/pipeline_core.cc',
      'pipeline/stage_if.cc',
      'pipeline/stage_id.cc',
      'pipeline/compressed_decode.cc',
      'pipeline/stage_ex.cc',
      'pipeline/stage_mem.cc',
      'pipeline/stage_wb.cc',
      'pipeline/frontend_fetch_unit.cc',
      'pipeline/hazard_unit.cc',
      'pipeline/forwarding_unit.cc',
      'pipeline/memory_backend_local.cc',
      'hc/hc_cbu.cc',
      'hc/hc_router.cc',
      'sau/sau_cbu.cc',
      'sau/stub_sau.cc',
      'veu/veu_cbu.cc',
      'veu/fake_veu.cc',
      'veu/timing_veu.cc',
      'veu/veu_functional.cc',
      'veu/veu_timing_profile.cc')
